cat > TradingViewBridge_EA.mq4 << 'EOF'
//+------------------------------------------------------------------+
//|                                            TradingViewBridge_EA.mq4 |
//|                        Generated by TradingView to MT4 Bridge v1.0   |
//|                                                                      |
//+------------------------------------------------------------------+
#property copyright "TradingView Bridge"
#property link      ""
#property version   "1.00"
#property strict

//+------------------------------------------------------------------+
//| Input parameters                                                 |
//+------------------------------------------------------------------+
input string   DataFolder = "Bridge_Data";     // Bridge Data Folder
input int      CheckInterval = 1;              // Check interval (seconds)
input bool     UseFileLogging = true;          // Enable file logging
input double   DefaultLotSize = 0.1;           // Default lot size
input int      Slippage = 3;                   // Slippage in points
input bool     AutoClose = true;               // Auto-close opposite positions
input string   MagicNumberStr = "TV_BRIDGE";   // Magic Number identifier
input bool     ShowAlerts = true;              // Show popup alerts
input double   MaxSpread = 50;                 // Maximum allowed spread (points)
input bool     UseRiskManagement = false;      // Enable risk management
input double   RiskPercent = 2.0;              // Risk % per trade (if UseRiskManagement=true)
input int      MaxDailyTrades = 0;             // Maximum trades per day (0=unlimited)

//+------------------------------------------------------------------+
//| Global variables                                                 |
//+------------------------------------------------------------------+
string lastProcessedFile = "";
datetime lastCheck = 0;
int magicNumber;
string dataPath;
string logPath;
string archivePath;
int dailyTradeCount = 0;
int lastTradeDay = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit() {
   // Create magic number from string
   magicNumber = 0;
   for(int i = 0; i < StringLen(MagicNumberStr); i++) {
      magicNumber += StringGetChar(MagicNumberStr, i);
   }
   
   // Setup paths
   dataPath = TerminalInfoString(TERMINAL_DATA_PATH) + "\\MQL4\\Files\\" + DataFolder + "\\";
   logPath = dataPath + "logs\\";
   archivePath = dataPath + "processed\\";
   
   // Create directories
   if(!FolderCreate(dataPath)) Print("Folder exists or cannot create: ", dataPath);
   if(!FolderCreate(logPath)) Print("Log folder exists or cannot create: ", logPath);
   if(!FolderCreate(archivePath)) Print("Archive folder exists or cannot create: ", archivePath);
   
   Print("═══════════════════════════════════════");
   Print("TradingView Bridge EA Initialized");
   Print("Data Path: ", dataPath);
   Print("Magic Number: ", magicNumber);
   Print("Check Interval: ", CheckInterval, " seconds");
   Print("═══════════════════════════════════════");
   
   LogMessage("EA initialized successfully");
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason) {
   LogMessage("EA deinitialized. Reason: " + IntegerToString(reason));
   Print("TradingView Bridge EA stopped");
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick() {
   // Check at specified interval
   if(TimeCurrent() - lastCheck >= CheckInterval) {
      lastCheck = TimeCurrent();
      CheckForSignals();
      
      // Reset daily trade counter
      int currentDay = DayOfYear();
      if(currentDay != lastTradeDay) {
         dailyTradeCount = 0;
         lastTradeDay = currentDay;
         LogMessage("Daily trade counter reset");
      }
   }
}

//+------------------------------------------------------------------+
//| Check for new signals from bridge                                |
//+------------------------------------------------------------------+
void CheckForSignals() {
   string searchPath = dataPath + "signal_*.json";
   string fileNames[];
   int totalFiles = 0;
   
   // Find all signal files
   long handle = FileFindFirst(searchPath, fileNames[0]);
   if(handle != INVALID_HANDLE) {
      do {
         totalFiles++;
         ArrayResize(fileNames, totalFiles);
         fileNames[totalFiles-1] = fileNames[0];
      } while(FileFindNext(handle, fileNames[0]));
      FileFindClose(handle);
   }
   
   // Process files in order (oldest first)
   if(totalFiles > 0) {
      ArraySort(fileNames);
      
      for(int i = 0; i < totalFiles; i++) {
         string filePath = dataPath + fileNames[i];
         ProcessSignalFile(filePath);
      }
   }
}

//+------------------------------------------------------------------+
//| Process a single signal file                                     |
//+------------------------------------------------------------------+
void ProcessSignalFile(string filePath) {
   int fileHandle = FileOpen(filePath, FILE_READ|FILE_TXT);
   if(fileHandle == INVALID_HANDLE) {
      Print("Failed to open file: ", filePath, " Error: ", GetLastError());
      return;
   }
   
   // Read JSON file content
   string content = "";
   while(!FileIsEnding(fileHandle)) {
      content += FileReadString(fileHandle);
   }
   FileClose(fileHandle);
   
   // Parse JSON
   string action = ParseJSONValue(content, "action");
   string symbol = ParseJSONValue(content, "symbol");
   double price = StringToDouble(ParseJSONValue(content, "price"));
   double quantity = StringToDouble(ParseJSONValue(content, "quantity"));
   string comment = ParseJSONValue(content, "comment");
   double stopLoss = StringToDouble(ParseJSONValue(content, "stopLoss"));
   double takeProfit = StringToDouble(ParseJSONValue(content, "takeProfit"));
   
   // Validate symbol
   if(symbol == "" || symbol == "UNKNOWN") {
      LogMessage("Invalid symbol in signal, using current chart symbol");
      symbol = Symbol();
   }
   
   // Market-specific symbol mapping
   symbol = MapSymbol(symbol);
   
   // Check if symbol exists in Market Watch
   if(!SymbolExists(symbol)) {
      LogMessage("Symbol " + symbol + " not found in Market Watch");
      return;
   }
   
   LogMessage(StringFormat("Signal received: %s %s at %.5f qty: %.2f SL: %.5f TP: %.5f", 
              action, symbol, price, quantity, stopLoss, takeProfit));
   
   // Execute trade based on action
   if(action == "BUY" || action == "LONG") {
      ExecuteBuy(symbol, quantity, price, comment, stopLoss, takeProfit);
   } 
   else if(action == "SELL" || action == "SHORT") {
      ExecuteSell(symbol, quantity, price, comment, stopLoss, takeProfit);
   }
   else if(action == "CLOSE") {
      CloseAllPositions(symbol);
   }
   
   // Move processed file to archive
   string archivedPath = archivePath + GetFileName(filePath);
   if(FileMove(filePath, 0, archivedPath, 0)) {
      LogMessage("File processed and archived: " + GetFileName(filePath));
   } else {
      LogMessage("Failed to archive file: " + GetFileName(filePath));
   }
}

//+------------------------------------------------------------------+
//| Execute BUY order                                                |
//+------------------------------------------------------------------+
void ExecuteBuy(string symbol, double lots, double price, string comment, double sl, double tp) {
   // Check daily trade limit
   if(MaxDailyTrades > 0 && dailyTradeCount >= MaxDailyTrades) {
      LogMessage("Daily trade limit reached: " + IntegerToString(MaxDailyTrades));
      if(ShowAlerts) Alert("Daily trade limit reached for " + symbol);
      return;
   }
   
   // Check spread
   if(!CheckSpread(symbol)) {
      LogMessage("Spread too high for " + symbol);
      return;
   }
   
   // Calculate lot size based on risk management
   if(UseRiskManagement && lots <= 0) {
      lots = CalculateLotSize(symbol, RiskPercent, sl);
      LogMessage("Risk-based lot size calculated: " + DoubleToString(lots, 2));
   }
   
   if(lots <= 0) lots = DefaultLotSize;
   if(price <= 0) price = MarketInfo(symbol, MODE_ASK);
   
   // Close opposite positions if enabled
   if(AutoClose) {
      ClosePositionsByType(symbol, OP_SELL);
   }
   
   // Prepare SL and TP
   int slPoints = 0;
   int tpPoints = 0;
   
   if(sl > 0) {
      slPoints = (int)MathRound((price - sl) / Point());
      if(slPoints < 0) slPoints = 0;
   }
   
   if(tp > 0) {
      tpPoints = (int)MathRound((tp - price) / Point());
      if(tpPoints < 0) tpPoints = 0;
   }
   
   int ticket = OrderSend(symbol, OP_BUY, lots, price, Slippage, 
                         slPoints > 0 ? price - slPoints * Point() : 0,
                         tpPoints > 0 ? price + tpPoints * Point() : 0,
                         "TV_Bridge_" + comment, magicNumber, 0, clrGreen);
   
   if(ticket > 0) {
      dailyTradeCount++;
      LogMessage(StringFormat("BUY order executed: %s %s %.2f lots at %.5f [Ticket: %d]", 
                 symbol, comment, lots, price, ticket));
      if(ShowAlerts) Alert("BUY order executed for " + symbol + " at " + DoubleToString(price, 5));
   } else {
      LogMessage(StringFormat("BUY order failed: %s Error: %d", 
                 symbol, GetLastError()));
      if(ShowAlerts) Alert("BUY order failed for " + symbol + " - Error: " + IntegerToString(GetLastError()));
   }
}

//+------------------------------------------------------------------+
//| Execute SELL order                                               |
//+------------------------------------------------------------------+
void ExecuteSell(string symbol, double lots, double price, string comment, double sl, double tp) {
   // Check daily trade limit
   if(MaxDailyTrades > 0 && dailyTradeCount >= MaxDailyTrades) {
      LogMessage("Daily trade limit reached: " + IntegerToString(MaxDailyTrades));
      if(ShowAlerts) Alert("Daily trade limit reached for " + symbol);
      return;
   }
   
   // Check spread
   if(!CheckSpread(symbol)) {
      LogMessage("Spread too high for " + symbol);
      return;
   }
   
   // Calculate lot size based on risk management
   if(UseRiskManagement && lots <= 0) {
      lots = CalculateLotSize(symbol, RiskPercent, sl);
      LogMessage("Risk-based lot size calculated: " + DoubleToString(lots, 2));
   }
   
   if(lots <= 0) lots = DefaultLotSize;
   if(price <= 0) price = MarketInfo(symbol, MODE_BID);
   
   // Close opposite positions if enabled
   if(AutoClose) {
      ClosePositionsByType(symbol, OP_BUY);
   }
   
   // Prepare SL and TP
   int slPoints = 0;
   int tpPoints = 0;
   
   if(sl > 0) {
      slPoints = (int)MathRound((sl - price) / Point());
      if(slPoints < 0) slPoints = 0;
   }
   
   if(tp > 0) {
      tpPoints = (int)MathRound((price - tp) / Point());
      if(tpPoints < 0) tpPoints = 0;
   }
   
   int ticket = OrderSend(symbol, OP_SELL, lots, price, Slippage,
                         slPoints > 0 ? price + slPoints * Point() : 0,
                         tpPoints > 0 ? price - tpPoints * Point() : 0,
                         "TV_Bridge_" + comment, magicNumber, 0, clrRed);
   
   if(ticket > 0) {
      dailyTradeCount++;
      LogMessage(StringFormat("SELL order executed: %s %s %.2f lots at %.5f [Ticket: %d]", 
                 symbol, comment, lots, price, ticket));
      if(ShowAlerts) Alert("SELL order executed for " + symbol + " at " + DoubleToString(price, 5));
   } else {
      LogMessage(StringFormat("SELL order failed: %s Error: %d", 
                 symbol, GetLastError()));
      if(ShowAlerts) Alert("SELL order failed for " + symbol + " - Error: " + IntegerToString(GetLastError()));
   }
}

//+------------------------------------------------------------------+
//| Close all positions for a symbol                                 |
//+------------------------------------------------------------------+
void CloseAllPositions(string symbol) {
   int closed = 0;
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
         if(OrderSymbol() == symbol && OrderMagicNumber() == magicNumber) {
            if(OrderClose(OrderTicket(), OrderLots(), OrderClosePrice(), Slippage, clrWhite)) {
               closed++;
               LogMessage("Closed position: Ticket " + IntegerToString(OrderTicket()));
            }
         }
      }
   }
   LogMessage(StringFormat("Closed %d positions for %s", closed, symbol));
   if(ShowAlerts && closed > 0) Alert("Closed " + IntegerToString(closed) + " positions for " + symbol);
}

//+------------------------------------------------------------------+
//| Close positions by type                                          |
//+------------------------------------------------------------------+
void ClosePositionsByType(string symbol, int type) {
   int closed = 0;
   for(int i = OrdersTotal() - 1; i >= 0; i--) {
      if(OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) {
         if(OrderSymbol() == symbol && OrderType() == type && OrderMagicNumber() == magicNumber) {
            if(OrderClose(OrderTicket(), OrderLots(), OrderClosePrice(), Slippage, clrWhite)) {
               closed++;
            }
         }
      }
   }
   if(closed > 0) LogMessage("Closed " + IntegerToString(closed) + " opposite positions");
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                      |
//+------------------------------------------------------------------+
double CalculateLotSize(string symbol, double riskPercent, double stopLoss) {
   double accountBalance = AccountBalance();
   double riskAmount = accountBalance * (riskPercent / 100.0);
   
   double tickValue = MarketInfo(symbol, MODE_TICKVALUE);
   double point = MarketInfo(symbol, MODE_POINT);
   
   double stopLossPoints = 0;
   if(stopLoss > 0) {
      double currentPrice = MarketInfo(symbol, MODE_BID);
      stopLossPoints = MathAbs(currentPrice - stopLoss) / point;
   } else {
      // Default stop loss: 50 points
      stopLossPoints = 50;
   }
   
   if(stopLossPoints <= 0) return DefaultLotSize;
   
   double lotSize = riskAmount / (stopLossPoints * tickValue);
   
   // Round to nearest allowed lot step
   double lotStep = MarketInfo(symbol, MODE_LOTSTEP);
   double minLot = MarketInfo(symbol, MODE_MINLOT);
   double maxLot = MarketInfo(symbol, MODE_MAXLOT);
   
   if(lotStep > 0) {
      lotSize = MathFloor(lotSize / lotStep) * lotStep;
   }
   
   if(lotSize < minLot) lotSize = minLot;
   if(lotSize > maxLot) lotSize = maxLot;
   
   return NormalizeDouble(lotSize, 2);
}

//+------------------------------------------------------------------+
//| Check if spread is acceptable                                    |
//+------------------------------------------------------------------+
bool CheckSpread(string symbol) {
   int currentSpread = (int)MathRound((MarketInfo(symbol, MODE_ASK) - MarketInfo(symbol, MODE_BID)) / Point());
   if(currentSpread > MaxSpread && MaxSpread > 0) {
      LogMessage("Spread too high: " + IntegerToString(currentSpread) + " points (max: " + IntegerToString(MaxSpread) + ")");
      return false;
   }
   return true;
}

//+------------------------------------------------------------------+
//| Map symbol names from TradingView to MT4                         |
//+------------------------------------------------------------------+
string MapSymbol(string symbol) {
   // Common mappings
   if(symbol == "EURUSD") return "EURUSD";
   if(symbol == "GBPUSD") return "GBPUSD";
   if(symbol == "USDJPY") return "USDJPY";
   if(symbol == "USDCHF") return "USDCHF";
   if(symbol == "USDCAD") return "USDCAD";
   if(symbol == "AUDUSD") return "AUDUSD";
   if(symbol == "NZDUSD") return "NZDUSD";
   if(symbol == "EURGBP") return "EURGBP";
   if(symbol == "EURJPY") return "EURJPY";
   if(symbol == "GBPJPY") return "GBPJPY";
   
   // Commodities
   if(symbol == "XAUUSD" || symbol == "GOLD") return "XAUUSD";
   if(symbol == "XAGUSD" || symbol == "SILVER") return "XAGUSD";
   
   // Indices
   if(symbol == "US30" || symbol == "DJI") return "US30";
   if(symbol == "SPX500" || symbol == "SPY") return "SPX500";
   if(symbol == "NAS100" || symbol == "NDX") return "NAS100";
   
   // Return as-is if no mapping found
   return symbol;
}

//+------------------------------------------------------------------+
//| Check if symbol exists in Market Watch                           |
//+------------------------------------------------------------------+
bool SymbolExists(string symbol) {
   // Try to select the symbol
   if(MarketInfo(symbol, MODE_BID) == 0) {
      // Try to add the symbol
      if(!SymbolSelect(symbol, true)) {
         return false;
      }
      // Wait a moment for symbol to load
      Sleep(100);
   }
   return true;
}

//+------------------------------------------------------------------+
//| Parse simple JSON values (basic implementation)                 |
//+------------------------------------------------------------------+
string ParseJSONValue(string json, string key) {
   string searchStr = "\"" + key + "\"";
   int pos = StringFind(json, searchStr);
   if(pos == -1) return "";
   
   pos = StringFind(json, ":", pos);
   if(pos == -1) return "";
   
   // Skip whitespace
   while(StringSubstr(json, pos + 1, 1) == " ") pos++;
   
   // Check if value is string or number
   string quote = StringSubstr(json, pos + 1, 1);
   int startPos = pos + 1;
   int endPos = -1;
   
   if(quote == "\"") {
      startPos++;
      endPos = StringFind(json, "\"", startPos);
   } else {
      // Number value
      endPos = startPos;
      while(endPos < StringLen(json)) {
         string ch = StringSubstr(json, endPos, 1);
         if(ch == "," || ch == "}" || ch == " " || ch == "\n" || ch == "\r") break;
         endPos++;
      }
   }
   
   if(endPos > startPos) {
      return StringSubstr(json, startPos, endPos - startPos);
   }
   
   return "";
}

//+------------------------------------------------------------------+
//| Get file name from path                                          |
//+------------------------------------------------------------------+
string GetFileName(string filePath) {
   int lastSlash = StringFind(filePath, "\\", StringLen(filePath) - 1);
   if(lastSlash == -1) lastSlash = StringFind(filePath, "/", StringLen(filePath) - 1);
   if(lastSlash != -1) {
      return StringSubstr(filePath, lastSlash + 1);
   }
   return filePath;
}

//+------------------------------------------------------------------+
//| Log message to file                                              |
//+------------------------------------------------------------------+
void LogMessage(string message) {
   string timestamp = TimeToString(TimeCurrent());
   string logEntry = timestamp + " - " + message;
   Print(logEntry);
   
   if(UseFileLogging) {
      string logFileName = logPath + "bridge_" + StringSubstr(TimeToString(TimeCurrent(), TIME_DATE), 0, 10) + ".log";
      int handle = FileOpen(logFileName, FILE_WRITE|FILE_READ|FILE_TXT);
      if(handle != INVALID_HANDLE) {
         FileSeek(handle, 0, SEEK_END);
         FileWrite(handle, logEntry);
         FileClose(handle);
      }
   }
}

//+------------------------------------------------------------------+
//| Get day of year                                                  |
//+------------------------------------------------------------------+
int DayOfYear() {
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   return dt.day_of_year;
}
//+------------------------------------------------------------------+
EOF
